"""
Builds excel/Churn_Retention_Model.xlsx
  Churn_Summary  : live COUNTIFS/AVERAGEIFS churn tables + charts + conditional formatting
  Retention_ROI  : scenario model (blue/yellow cells are inputs) turning model scores into Rs impact
  Customer_Scores: 6,000 customers with out-of-fold churn probability and risk tier (Excel Table)
Run AFTER analysis.py:  python python/build_excel.py
"""
from pathlib import Path
import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.comments import Comment
from openpyxl.formatting.rule import ColorScaleRule, CellIsRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.worksheet.table import Table, TableStyleInfo

ROOT = Path(__file__).resolve().parents[1]
d = pd.read_csv(ROOT / "data/processed/churn_scores.csv")
cols = ["customer_id", "contract", "internet_service", "tenure_band", "tenure_months", "payment_method",
        "monthly_charges", "ticket_count", "churned", "churn_probability", "risk_tier"]
d = d[cols]; n = len(d) + 1
F = "Arial"
B = Font(name=F, bold=True); N = Font(name=F)
HF, HP = Font(name=F, bold=True, color="FFFFFF"), PatternFill("solid", fgColor="1F4E79")
IF_, IP = Font(name=F, bold=True, color="0000FF"), PatternFill("solid", fgColor="FFFF00")
th = Side(style="thin", color="BFBFBF"); BD = Border(top=th, bottom=th, left=th, right=th)
wb = Workbook()

# ---------------- README
ws = wb.active; ws.title = "README"
info = [("Telecom Churn - Retention Model (Excel)", None),
        ("Purpose", "Quantifies churn drivers and the $ return of a targeted retention campaign using model scores."),
        ("Currency", "Monthly charges in the dataset range $18-$125, so money is shown in $."),
        ("Data", "SYNTHETIC data (6,000 customers) generated by python/generate_data.py - not real customers. Scores are out-of-fold logistic-regression probabilities."),
        ("Sheets", "Churn_Summary (formulas) | Retention_ROI (scenario model) | Customer_Scores (data table tblScores)"),
        ("Legend", "Blue bold on yellow = input assumption you can change. Black = formula. Every input is an ASSUMPTION - replace with your company's real numbers."),
        ("Key assumption", "A customer with churned = 0 is treated as an ACTIVE customer who can still be targeted; churned = 1 customers have already left.")]
for i, (a, b) in enumerate(info, 1):
    ws.cell(i, 1, a).font = Font(name=F, bold=True, size=14 if i == 1 else 11)
    if b: ws.cell(i, 2, b).font = N; ws.cell(i, 2).alignment = Alignment(wrap_text=True, vertical="top"); ws.row_dimensions[i].height = 32
ws.column_dimensions["A"].width = 18; ws.column_dimensions["B"].width = 110

# ---------------- DATA
wd = wb.create_sheet("Customer_Scores")
wd.append(cols)
for r in d.itertuples(index=False):
    wd.append([r.customer_id, r.contract, r.internet_service, r.tenure_band, int(r.tenure_months), r.payment_method,
               float(r.monthly_charges), int(r.ticket_count), int(r.churned), float(r.churn_probability), r.risk_tier])
for c in wd[1]: c.font, c.fill = HF, HP
for row in wd.iter_rows(min_row=2, max_row=n):
    row[6].number_format = "#,##0.00"; row[9].number_format = "0.0%"
for col, w in zip("ABCDEFGHIJK", [11, 16, 16, 14, 13, 17, 15, 12, 9, 16, 11]): wd.column_dimensions[col].width = w
t = Table(displayName="tblScores", ref=f"A1:K{n}"); t.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
wd.add_table(t); wd.freeze_panes = "A2"
R = lambda c: f"Customer_Scores!${c}$2:${c}${n}"
CON, INT, TEN, PAY, MON, TIX, CH, PR, TIER = (R(c) for c in "BCDFGHIJK")

# ---------------- SUMMARY
s = wb.create_sheet("Churn_Summary", 1)
s["A1"] = "Churn Summary"; s["A1"].font = Font(name=F, bold=True, size=16)
def head(r, labels, c0=1):
    for i, l in enumerate(labels):
        x = s.cell(r, c0 + i, l); x.font, x.fill, x.border = HF, HP, BD; x.alignment = Alignment(horizontal="center", wrap_text=True)
head(3, ["KPI", "Value"])
k = [("Customers", f"=COUNTA({R('A')})", "#,##0"), ("Churned customers", f"=SUM({CH})", "#,##0"),
     ("Churn rate", "=B5/B4", "0.0%"), ("Monthly revenue lost ($)", f"=SUMIFS({MON},{CH},1)", "#,##0"),
     ("Monthly revenue retained ($)", f"=SUMIFS({MON},{CH},0)", "#,##0"), ("Avg monthly charge ($)", f"=AVERAGE({MON})", "#,##0.0")]
for i, (l, f, nf) in enumerate(k, 4):
    s.cell(i, 1, l).font = B; c = s.cell(i, 2, f); c.number_format, c.font = nf, N; s.cell(i, 1).border = c.border = BD

def seg_table(r0, title, rng, items):
    head(r0, [title, "Customers", "Churned", "Churn rate", "Index vs avg"])
    for i, it in enumerate(items, r0 + 1):
        s.cell(i, 1, it).font = B
        s.cell(i, 2, f'=COUNTIFS({rng},$A{i})').number_format = "#,##0"
        s.cell(i, 3, f'=COUNTIFS({rng},$A{i},{CH},1)').number_format = "#,##0"
        s.cell(i, 4, f"=C{i}/B{i}").number_format = "0.0%"
        s.cell(i, 5, f"=D{i}/$B$6").number_format = "0.00"
    last = r0 + len(items)
    s.conditional_formatting.add(f"D{r0+1}:D{last}", ColorScaleRule(start_type="min", start_color="63BE7B", mid_type="percentile", mid_value=50, mid_color="FFEB84", end_type="max", end_color="F8696B"))
    return last
e1 = seg_table(12, "Contract", CON, ["Month-to-month", "One year", "Two year"])
e2 = seg_table(18, "Tenure band", TEN, ["0-12 months", "13-24 months", "25-48 months", "49+ months"])
e3 = seg_table(25, "Internet service", INT, ["Fiber optic", "DSL", "No internet"])
e4 = seg_table(31, "Payment method", PAY, ["Electronic check", "Credit card", "Bank transfer", "Mailed check"])
s["A37"] = "Index vs avg: 1.00 = average churn; 1.60 means 60% more likely to churn than the average customer."; s["A37"].font = Font(name=F, italic=True, size=9)
for ch_, anchor, (r0, r1), title in ((BarChart(), "H3", (12, e1), "Churn rate by contract"), (BarChart(), "H19", (18, e2), "Churn rate by tenure band")):
    ch_.type, ch_.title, ch_.height, ch_.width, ch_.legend = "col", title, 7, 12, None
    ch_.add_data(Reference(s, min_col=4, min_row=r0, max_row=r1), titles_from_data=True)
    ch_.set_categories(Reference(s, min_col=1, min_row=r0 + 1, max_row=r1)); ch_.y_axis.numFmt = "0%"; s.add_chart(ch_, anchor)
for col, w in zip("ABCDE", [30, 14, 12, 12, 14]): s.column_dimensions[col].width = w

# ---------------- ROI MODEL
m = wb.create_sheet("Retention_ROI", 2)
m["A1"] = "Retention Campaign ROI Model"; m["A1"].font = Font(name=F, bold=True, size=16)
m["A2"] = "Yellow cells are ASSUMPTIONS (not facts). Change them and everything below recalculates."; m["A2"].font = Font(name=F, italic=True)
inputs = [("Save rate (share of would-be churners retained when contacted)", 0.25, "0%", "Assumption - typical campaign range 10-40%. Replace with A/B-test result."),
          ("Discount offered on monthly bill", 0.15, "0%", "Assumption - retention offer."),
          ("Offer duration (months)", 6, "0", "Assumption."),
          ("Contact cost per customer ($)", 5, "#,##0.00", "Assumption - call / SMS / agent time."),
          ("Months a saved customer stays after the offer", 12, "0", "Assumption - lifetime extension."),
          ("Contribution margin on revenue", 0.50, "0%", "Assumption - share of revenue that is profit after network cost."),
          ("Offer take-up rate (share of contacted customers who accept the discount)", 0.30, "0%", "Assumption - only customers who accept cost you the discount. Must be >= save rate for consistency.")]
for i, (l, v, nf, note) in enumerate(inputs, 4):
    m.cell(i, 1, l).font = B; c = m.cell(i, 2, v); c.number_format, c.font, c.fill, c.border = nf, IF_, IP, BD
    c.comment = Comment(note, "Analyst"); m.cell(i, 3, note).font = Font(name=F, italic=True, size=9, color="595959")
SAVE, DISC, DUR, CONT, LIFE, MARG, TAKE = (f"$B${r}" for r in range(4, 11))

# tier table
for i, l in enumerate(["Risk tier (active customers only)", "Active customers", "Expected churners", "Monthly revenue ($)", "Avg monthly charge ($)"]):
    c = m.cell(12, 1 + i, l); c.font, c.fill, c.border = HF, HP, BD; c.alignment = Alignment(wrap_text=True, horizontal="center")
for i, tier in enumerate(["High", "Medium", "Low"], 13):
    m.cell(i, 1, tier).font = B
    m.cell(i, 2, f'=COUNTIFS({TIER},$A{i},{CH},0)').number_format = "#,##0"
    m.cell(i, 3, f'=SUMIFS({PR},{TIER},$A{i},{CH},0)').number_format = "#,##0.0"
    m.cell(i, 4, f'=SUMIFS({MON},{TIER},$A{i},{CH},0)').number_format = "#,##0"
    m.cell(i, 5, f"=D{i}/B{i}").number_format = "#,##0.0"

# scenarios
hd = ["Scenario", "Include High (1/0)", "Include Medium (1/0)", "Include Low (1/0)", "Customers contacted", "Expected churners among them",
      "Expected customers saved", "Avg monthly charge ($)", "Profit retained ($)", "Contact cost ($)", "Offer cost ($) = contacted x take-up x avg bill x discount x months", "Total cost ($)", "Net benefit ($)", "ROI"]
for i, l in enumerate(hd):
    c = m.cell(18, 1 + i, l); c.font, c.fill, c.border = HF, HP, BD; c.alignment = Alignment(wrap_text=True, horizontal="center", vertical="center")
m.row_dimensions[18].height = 45
sc = [("A: High tier only", 1, 0, 0), ("B: High + Medium", 1, 1, 0), ("C: Everyone", 1, 1, 1)]
for i, (nm, h, md, lo) in enumerate(sc, 19):
    m.cell(i, 1, nm).font = B
    for j, v in enumerate((h, md, lo), 2):
        c = m.cell(i, j, v); c.font, c.fill, c.border = IF_, IP, BD
    m.cell(i, 5, f"=B{i}*$B$13+C{i}*$B$14+D{i}*$B$15").number_format = "#,##0"
    m.cell(i, 6, f"=B{i}*$C$13+C{i}*$C$14+D{i}*$C$15").number_format = "#,##0.0"
    m.cell(i, 7, f"=F{i}*{SAVE}").number_format = "#,##0.0"
    m.cell(i, 8, f"=(B{i}*$D$13+C{i}*$D$14+D{i}*$D$15)/E{i}").number_format = "#,##0.0"
    m.cell(i, 9, f"=G{i}*H{i}*{LIFE}*{MARG}").number_format = "#,##0"
    m.cell(i, 10, f"=E{i}*{CONT}").number_format = "#,##0"
    m.cell(i, 11, f"=E{i}*{TAKE}*H{i}*{DISC}*{DUR}").number_format = "#,##0"
    m.cell(i, 12, f"=J{i}+K{i}").number_format = "#,##0"
    m.cell(i, 13, f"=I{i}-L{i}").number_format = "#,##0;[Red]-#,##0"
    m.cell(i, 14, f"=M{i}/L{i}").number_format = "0%;[Red]-0%"
    for j in range(5, 15): m.cell(i, j).font = N; m.cell(i, j).border = BD
m["A23"] = "Best scenario by net benefit"; m["A23"].font = B
m["B23"] = "=INDEX($A$19:$A$21,MATCH(MAX($M$19:$M$21),$M$19:$M$21,0))"; m["B23"].font = Font(name=F, bold=True, color="C00000")
m["A25"] = "Best scenario by ROI"; m["A25"].font = B
m["B25"] = "=INDEX($A$19:$A$21,MATCH(MAX($N$19:$N$21),$N$19:$N$21,0))"; m["B25"].font = Font(name=F, bold=True, color="C00000")
m["A24"] = "Why not 'Everyone'? Low-risk customers rarely churn, so contact and offer cost is mostly wasted - the model's value is targeting."; m["A24"].font = Font(name=F, italic=True, size=9)

# sensitivity (scenario A)
m["A27"] = "Sensitivity - Scenario A net benefit vs save rate"; m["A27"].font = Font(name=F, bold=True, size=12)
for i, l in enumerate(["Save rate", "Net benefit ($)", "ROI"]):
    c = m.cell(28, 1 + i, l); c.font, c.fill, c.border = HF, HP, BD
for i, sr in enumerate([0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40], 29):
    m.cell(i, 1, sr).number_format = "0%"; m.cell(i, 1).font = B
    m.cell(i, 2, f"=$F$19*A{i}*$H$19*{LIFE}*{MARG}-$L$19").number_format = "#,##0;[Red]-#,##0"
    m.cell(i, 3, f"=B{i}/$L$19").number_format = "0%;[Red]-0%"
m["A36"] = "Break-even save rate (Scenario A)"; m["A36"].font = B
m["B36"] = f"=$L$19/($F$19*$H$19*{LIFE}*{MARG})"; m["B36"].number_format = "0.0%"
m.conditional_formatting.add("M19:M21", CellIsRule(operator="lessThan", formula=["0"], font=Font(name=F, color="C00000", bold=True)))
bc = BarChart(); bc.type, bc.title, bc.height, bc.width, bc.legend = "col", "Net benefit by scenario ($)", 7, 13, None
bc.add_data(Reference(m, min_col=13, min_row=18, max_row=21), titles_from_data=True); bc.set_categories(Reference(m, min_col=1, min_row=19, max_row=21)); m.add_chart(bc, "F27")
m.column_dimensions["A"].width = 58
for col in "BCDEFGHIJKLMN": m.column_dimensions[col].width = 15

out = ROOT / "excel/Churn_Retention_Model.xlsx"; wb.save(out); print("saved", out)
